image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HUB_USER: '$DOCKER_HUB_USERNAME'
  DOCKER_HUB_PASSWORD: '$DOCKER_HUB_PASSWORD'
  SERVER_IP: '$SERVER_IP'
  SERVER_USER: root
  SSH_PRIVATE_KEY: '$SSH_PRIVATE_KEY'

stages:
  - build
  - deploy

build:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - echo "Building Docker image..."
    - sh ./env-as-build-args.sh $ENV_FILE | xargs docker build -t $DOCKER_HUB_USER/digital-back:latest .
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
    - docker push $DOCKER_HUB_USER/digital-back:latest

deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
  script:
    - source $ENV_FILE
    - echo $PORT
    - echo $REDIS_PASSWORD
    - >
      ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP '
        ENV_ARGS=""
        while IFS= read -r line; do
          if [[ ! -z "$line" && "$line" != \#* ]]; then
            VAR="-e $line"
            ENV_ARGS="$ENV_ARGS $VAR"
          fi
        done < <(echo "$ENV_FILE")
        docker pull $DOCKER_HUB_USER/digital-back:latest &&
        docker stop back || true &&
        docker rm back || true &&
        docker run -d --restart unless-stopped $ENV_ARGS --net host -p 127.0.0.1:8000:8000 --name back $DOCKER_HUB_USER/digital-back:latest
      '
    # - ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP "docker pull $DOCKER_HUB_USER/digital-back:latest && docker stop back || true && docker rm back || true && bash ./env-as-e.sh $ENV_FILE | xargs docker run -d --restart unless-stopped --net host -p 127.0.0.1:8000:8000 --name back $DOCKER_HUB_USER/digital-back:latest"
    # - ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP "docker system prune -a -f"
