image: docker:stable

# services:
#   - docker:dind

variables:
  DOCKER_HUB_USER: '$DOCKER_HUB_USERNAME'
  DOCKER_HUB_PASSWORD: '$DOCKER_HUB_PASSWORD'
  SERVER_IP: '$SERVER_IP'
  SERVER_USER: root
  SSH_PRIVATE_KEY: '$SSH_PRIVATE_KEY'

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH ==  "main"
      variables:
        ENVIRONMENT_NAME: production
        HOST: igniz.ru
    - if: $CI_COMMIT_BRANCH == "stage"
      variables:
        ENVIRONMENT_NAME: stage
        HOST: igniz.ru
    - when: always

stages:
  - build
  - deploy

build:
  stage: build
  environment:
    name: $ENVIRONMENT_NAME
  tags:
    - $ENVIRONMENT_NAME
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - echo "Building Docker image..."
    - sh ./env-as-build-args.sh $ENV_FILE | xargs docker build -t $TAG_COMMIT -t $TAG_LATEST .
    # - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
    # - docker push $DOCKER_HUB_USER/digital-back:latest

deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
  tags:
    - $ENVIRONMENT_NAME
  # before_script:
  #   - mkdir -p ~/.ssh
  #   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  #   - chmod 600 ~/.ssh/id_rsa
  #   - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
  script:
    - docker container rm -f $IMGNAME || true
    - source $ENV_FILE
    - docker run -d --restart unless-stopped  --net host -p 127.0.0.1:$PORT_BACKEND:$PORT_BACKEND  --name $IMGNAME $TAG_COMMIT
  after_script:
    - docker system prune -a -f
      # - ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP "docker pull $DOCKER_HUB_USER/digital-back:latest && docker stop back || true && docker rm back || true && docker run -d --restart unless-stopped --net host -p 127.0.0.1:8000:8000 --name back $DOCKER_HUB_USER/digital-back:latest"
      # - ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP "docker system prune -a -f"
