variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

services:
  - name: docker:dind
    command: ["--tls=false", "--host=tcp://0.0.0.0:2375"]

stages:
  - build
  - deploy

build:
  image: docker:24.0  # Используем конкретную версию вместо :stable
  stage: build
  environment:
    name: $ENVIRONMENT_NAME
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "stage"
  script:
    - docker info
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST

deploy:
  image: docker:24.0
  stage: deploy
  environment:
    name: $ENVIRONMENT_NAME
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
    - docker pull $TAG_COMMIT
    - docker container rm -f $IMGNAME || true
    - docker run -d --restart unless-stopped -p 5173:5173 --name $IMGNAME $TAG_COMMIT