services:
  - docker:dind

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  IMGNAME: "digital-front"
  DOCKER_HUB_USER: "$DOCKER_HUB_USERNAME"
  DOCKER_HUB_PASSWORD: "$DOCKER_HUB_PASSWORD"
  # SERVER_IP: "$SERVER_IP"
  # SERVER_USER: root
  # SSH_PRIVATE_KEY: "$SSH_PRIVATE_KEY"

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH ==  "main"
      variables:
        ENVIRONMENT_NAME: production
        HOST: igniz.ru
    - if: $CI_COMMIT_BRANCH == "stage"
      variables:
        ENVIRONMENT_NAME: stage
        HOST: igniz.ru

stages:
  - build
  - deploy

build:
  image: docker:stable
  stage: build
  environment:
    name: $ENVIRONMENT_NAME
  tags:
    - $ENVIRONMENT_NAME
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
    - echo "Building Docker image..."
    - sh ./env-as-build-args.sh $ENV_FILE | xargs docker build -t $TAG_COMMIT -t $TAG_LATEST .
    # - docker push $TAG_COMMIT
    # - docker push $TAG_LATEST
    # - docker build -t $DOCKER_HUB_USER/digital-front:latest .
    # - docker push $DOCKER_HUB_USER/digital-front:latest

deploy:
  image: docker:stable
  stage: deploy
  tags:
    - $ENVIRONMENT_NAME
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
  # before_script:
  # - mkdir -p ~/.ssh
  # - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  # - chmod 600 ~/.ssh/id_rsa
  # - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
    - docker container rm -f $IMGNAME || true
    - source $ENV_FILE
    - echo $BASE_API_URL
    - docker run -d --restart unless-stopped --env-file $ENV_FILE -p 5173:5173 --name $IMGNAME $TAG_COMMIT
    # - docker run -d --restart unless-stopped -p 5173:5173 --name $IMGNAME $TAG_COMMIT
    # - ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP "docker pull $DOCKER_HUB_USER/digital-front:latest && docker stop front || true && docker rm front || true && docker run -d -p 5173:5173 --name front $DOCKER_HUB_USER/digital-front:latest"
    # - ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP "docker system prune -a -f"
  after_script:
    - docker system prune -a -f
